---
- name: Ensure directory for self-signed cert exists
  become: yes
  file:
    state: directory
    path: "{{ certbot_stubs_root }}"
    owner: root
    mode: 0700

- name: Generate private key
  become: yes
  command:
    cmd: openssl genrsa -out {{ certbot_stub_key_file }} {{ ssl_key_length | default(2048) }}
    creates: "{{ certbot_stub_key_file }}"
  register: ssl_private_key_status

- name: Render CSR config
  become: yes
  template:
    src: "{{ csr_config_template }}"
    dest: "{{ certbot_selfsigned_csr_config_file }}"
    owner: root
    mode: 0600
  register: csr_config_status

- name: Remove CSR if key or config has changed
  become: yes
  file:
    path: "{{ certbot_selfsigned_csr_file }}"
    state: absent
  when: ssl_private_key_status is changed or csr_config_status is changed

- name: Generate CSR
  become: yes
  command:
    cmd: openssl req -new -key {{ certbot_stub_key_file }} -out {{ certbot_selfsigned_csr_file }} -config {{ certbot_selfsigned_csr_config_file }}
    creates: "{{ certbot_selfsigned_csr_file }}"
  register: csr_status

- name: Ensure file permissions for CSR
  become: yes
  file:
    path: "{{ certbot_selfsigned_csr_file }}"
    owner: root
    mode: 0600

- name: Remove a certificate if CSR changes
  become: yes
  file:
    path: "{{ certbot_stub_cert_file }}"
    state: absent
  when: csr_status is changed

- name: Issue a self-signed certificate
  become: yes
  command:
    cmd: "openssl x509 -in {{ certbot_selfsigned_csr_file }} -out {{ certbot_stub_cert_file }} -req -signkey {{ certbot_stub_key_file }} -days 365"
    creates: "{{ certbot_stub_cert_file }}"
